services:
  - type: web
    name: flask-login-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false  # Set manually in Render dashboard
