services:
  - type: web
    name: facebook-post-id-extractor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn facebook_post_uid_service:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
